# Generated by Django 4.1.3 on 2023-04-17 10:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_tag_id_alter_taggeditem_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kатегоpии',
                'verbose_name_plural': 'Kaтегоpии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Название коллекции')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Коллекции',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(db_index=True, max_length=100, verbose_name='Подкатегория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Общее описание')),
                ('structure', models.TextField(blank=True, verbose_name='Состав')),
                ('care', models.TextField(blank=True, verbose_name='Уход')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото3')),
                ('sale', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('price', models.IntegerField(verbose_name='Ценa')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('collecproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.collections', verbose_name='Выберите коллекцию')),
                ('prod_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category', verbose_name='Выберите категорию')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.subcategory', verbose_name='Выберите подкатегорю')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
